package jobreport

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

// JobInfo is everything we can recover from a GitLab job.log + its artifact URL.
type JobInfo struct {
	JobID     string
	TraceID   string
	Date      string // YYYY_MM_DD from the URL
	JobName   string
	JobSlug   string
	Pipeline  string
	Project   string
	Runner    string // e.g. vsphere_kuber_runner_with_shm
	Shard     string // e.g. glrtr-jv
	SystemID  string
	Executor  string // kubernetes / shell / ...
	Pod       string
	Namespace string

	StartEpoch int64
	EndEpoch   int64
	Phases     []Phase

	Failed   bool
	FailMsg  string
	ExitCode string

	CrashKill   bool     // "force-killing DS processes"
	CoreCmdline string   // from `Core was generated by `...``
	CrashFrames []string // top backtrace frames
	KilledNames []string // distinct DS process names that were force-killed
	KillPIDs    []string // pids referenced by kill_process

	Artifacts map[string]string // label -> download URL
}

type Phase struct {
	Name       string
	Start, End int64
}

func (j JobInfo) Duration() int64 {
	if j.EndEpoch > j.StartEpoch {
		return j.EndEpoch - j.StartEpoch
	}
	return 0
}

var (
	reANSI     = regexp.MustCompile(`\x1b\[[0-9;]*[A-Za-z]`)
	reURLParts = regexp.MustCompile(`/(\d{4}_\d{2}_\d{2})/(\d+)/(\d+)/job\.log`)
	reRunner   = regexp.MustCompile(`on (\S+) (glrtr-\S+), system ID: (\S+)`)
	reExecutor = regexp.MustCompile(`Preparing the "(\w+)" executor`)
	rePod      = regexp.MustCompile(`pod (\S+)/(\S+) to be running`)
	reJobIDURL = regexp.MustCompile(`/-/jobs/(\d+)`)
	reMinio    = regexp.MustCompile(`/(\d+)/logs/([^/]+)/(\d+)/`)
	reProjLog  = regexp.MustCompile(`/builds/([^/]+)/([^/]+)/`)
	reSection  = regexp.MustCompile(`section_(start|end):(\d+):([a-zA-Z_]+)`)
	reFail     = regexp.MustCompile(`ERROR: Job failed: (.+)`)
	reExit     = regexp.MustCompile(`exit code (\d+)`)
	reCore     = regexp.MustCompile("Core was generated by `(.+)'")
	reFrame    = regexp.MustCompile(`^#(\d+)\s+(?:0x[0-9a-fA-F]+ in )?(.+)$`)
	reKillName = regexp.MustCompile(`process_name = '([^']+)'`)
	reKillPID  = regexp.MustCompile(`process_id = (\d+)`)
	reArtifact = regexp.MustCompile(`^(https://\S+?/([^/]+\.(?:zip|db)))/`)
)

// fetchLog downloads a job.log URL (or, if it points at a local file, reads it).
// Presigned job-log URLs expire within minutes, so reading a saved copy from disk
// — either a bare path or a file:// URL — keeps the same report reproducible.
func fetchLog(jobURL string) ([]byte, error) {
	if path, ok := localPath(jobURL); ok {
		return os.ReadFile(path)
	}
	cl := &http.Client{Timeout: 60 * time.Second}
	req, err := http.NewRequestWithContext(context.Background(), http.MethodGet, jobURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := cl.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == http.StatusForbidden {
		return nil, fmt.Errorf("HTTP 403 (presigned URL likely expired — regenerate the job-log link)")
	}
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("HTTP %d fetching job log", resp.StatusCode)
	}
	return body, nil
}

// localPath reports whether src refers to a local file rather than an http(s)
// endpoint, returning the filesystem path to read. A file:// URL is always local;
// anything without an http(s) scheme is treated as a bare path.
func localPath(src string) (string, bool) {
	if p, ok := strings.CutPrefix(src, "file://"); ok {
		return p, true
	}
	if strings.HasPrefix(src, "http://") || strings.HasPrefix(src, "https://") {
		return "", false
	}
	return src, true
}

func stripANSI(s string) string { return reANSI.ReplaceAllString(s, "") }

// parseJobLog parses the raw (ANSI-containing) log bytes plus the source URL.
func parseJobLog(raw []byte, jobURL string) JobInfo {
	var j JobInfo
	j.Artifacts = map[string]string{}

	if m := reURLParts.FindStringSubmatch(jobURL); m != nil {
		j.Date, j.JobID, j.TraceID = m[1], m[2], m[3]
	}

	clean := stripANSI(string(raw))
	lines := strings.Split(clean, "\n")

	phaseStart := map[string]int64{}
	var frameNums []int
	frameByNum := map[int]string{}

	for _, ln := range lines {
		if m := reRunner.FindStringSubmatch(ln); m != nil {
			j.Runner, j.Shard, j.SystemID = m[1], m[2], m[3]
		}
		if m := reExecutor.FindStringSubmatch(ln); m != nil && j.Executor == "" {
			j.Executor = m[1]
		}
		if m := rePod.FindStringSubmatch(ln); m != nil && j.Pod == "" {
			j.Namespace, j.Pod = m[1], m[2]
		}
		if j.JobID == "" {
			if m := reJobIDURL.FindStringSubmatch(ln); m != nil {
				j.JobID = m[1]
			}
		}
		if m := reMinio.FindStringSubmatch(ln); m != nil {
			j.Pipeline, j.JobSlug = m[1], m[2]
			if j.JobID == "" {
				j.JobID = m[3]
			}
		}
		if j.Project == "" {
			if m := reProjLog.FindStringSubmatch(ln); m != nil {
				j.Project = m[1] + "/" + m[2]
			}
		}
		for _, m := range reSection.FindAllStringSubmatch(ln, -1) {
			kind, name := m[1], m[3]
			ep, _ := strconv.ParseInt(m[2], 10, 64)
			if j.StartEpoch == 0 || ep < j.StartEpoch {
				j.StartEpoch = ep
			}
			if ep > j.EndEpoch {
				j.EndEpoch = ep
			}
			if kind == "start" {
				phaseStart[name] = ep
			} else if st, ok := phaseStart[name]; ok {
				j.Phases = append(j.Phases, Phase{Name: name, Start: st, End: ep})
				delete(phaseStart, name)
			}
		}
		if m := reFail.FindStringSubmatch(ln); m != nil {
			j.Failed, j.FailMsg = true, strings.TrimSpace(m[1])
			if e := reExit.FindStringSubmatch(m[1]); e != nil {
				j.ExitCode = e[1]
			}
		}
		if strings.Contains(ln, "force-killing DS processes") {
			j.CrashKill = true
		}
		if m := reCore.FindStringSubmatch(ln); m != nil && j.CoreCmdline == "" {
			j.CoreCmdline = m[1]
		}
		if m := reFrame.FindStringSubmatch(strings.TrimSpace(ln)); m != nil {
			n, _ := strconv.Atoi(m[1])
			if _, dup := frameByNum[n]; !dup {
				frameByNum[n] = strings.TrimSpace(m[2])
				frameNums = append(frameNums, n)
			}
		}
		if m := reKillName.FindStringSubmatch(ln); m != nil && !contains(j.KilledNames, m[1]) {
			j.KilledNames = append(j.KilledNames, m[1])
		}
		if m := reKillPID.FindStringSubmatch(ln); m != nil && !contains(j.KillPIDs, m[1]) {
			j.KillPIDs = append(j.KillPIDs, m[1])
		}
		if m := reArtifact.FindStringSubmatch(ln); m != nil {
			label := m[2]
			if _, ok := j.Artifacts[label]; !ok {
				j.Artifacts[label] = m[1]
			}
		}
	}

	// top backtrace frames (lowest frame numbers first)
	sort.Ints(frameNums)
	for i, n := range frameNums {
		if i >= 5 {
			break
		}
		j.CrashFrames = append(j.CrashFrames, fmt.Sprintf("#%d %s", n, frameByNum[n]))
	}

	if j.Date == "" && j.StartEpoch > 0 {
		j.Date = time.Unix(j.StartEpoch, 0).UTC().Format("2006_01_02")
	}
	return j
}
